version: 2

python:
  version: "3.7"
  install:
    - requirements: requirements/requirements.txt
    - requirements: requirements/extras_all.txt

# Build documentation in the source/ directory with Sphinx
sphinx:
  configuration: docs/source/conf.py

build:
  image: latest

# Setup submodules
submodules:
  include: all
