name: Codecov test coverage
on: [push]
jobs:
  my-job:
    name: Codecov
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: codecov/codecov-action@v3
        with:
          token: dbf8103a-6920-4bdc-80cc-2917fafc68e7
          directory: ./tests
          files: ./coverage.xml
          verbose: true